// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3G56roKDRkLr6x1x1bdoDdb9M3dU2J1I',
    appId: '1:15283861993:web:db1ec1b9ba47b6d75b7378',
    messagingSenderId: '15283861993',
    projectId: 'animevault-97456',
    authDomain: 'animevault-97456.firebaseapp.com',
    storageBucket: 'animevault-97456.firebasestorage.app',
    measurementId: 'G-HW5Y85F0VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ6wUedYCPYnHQF3bXCr-ZJFk1vutfBlg',
    appId: '1:15283861993:android:650d4f66f93b4c3b5b7378',
    messagingSenderId: '15283861993',
    projectId: 'animevault-97456',
    storageBucket: 'animevault-97456.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA33YmwadxOC3B8IB5I4GazBUAG9GXnOxs',
    appId: '1:15283861993:ios:17bc9f62b5895d3f5b7378',
    messagingSenderId: '15283861993',
    projectId: 'animevault-97456',
    storageBucket: 'animevault-97456.firebasestorage.app',
    iosBundleId: 'com.example.animevault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA33YmwadxOC3B8IB5I4GazBUAG9GXnOxs',
    appId: '1:15283861993:ios:a7eb9ed75fd0fd885b7378',
    messagingSenderId: '15283861993',
    projectId: 'animevault-97456',
    storageBucket: 'animevault-97456.firebasestorage.app',
    iosBundleId: 'com.example.ainmeVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3G56roKDRkLr6x1x1bdoDdb9M3dU2J1I',
    appId: '1:15283861993:web:93f40e36292596515b7378',
    messagingSenderId: '15283861993',
    projectId: 'animevault-97456',
    authDomain: 'animevault-97456.firebaseapp.com',
    storageBucket: 'animevault-97456.firebasestorage.app',
    measurementId: 'G-5TQBP8LYZZ',
  );
}
